application: campusfeed
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: static/js
- url: /js/lib
  static_dir: static/js/lib
- url: /js/controllers
  static_dir: static/js/controllers
- url: /js/services
  static_dir: static/js/services
- url: /js/directives
  static_dir: static/js/directives
- url: /css
  static_dir: static/css
- url: /fonts
  static_dir: static/fonts
- url: /html
  static_dir: static/html
- url: /images
  static_dir: static/images
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: yaml
  version: latest
- name: django
  version: latest
- name: pycrypto
  version: latest